#pragma once
enum Anchor
{
    ANCHOR_CENTER = 0x0,

    ANCHOR_TOP = 0x1,
    ANCHOR_BOTTOM = 0x2,
    ANCHOR_LEFT = 0x4,
    ANCHOR_RIGHT = 0x8,

    ANCHOR_TOP_LEFT = ANCHOR_TOP | ANCHOR_LEFT,
    ANCHOR_TOP_RIGHT = ANCHOR_TOP | ANCHOR_RIGHT,
    ANCHOR_BOTTOM_LEFT = ANCHOR_BOTTOM | ANCHOR_LEFT,
    ANCHOR_BOTTOM_RIGHT = ANCHOR_BOTTOM | ANCHOR_RIGHT,
};

