#pragma once
enum KtCuller3DField : char
{
	KT_CULLER_3D_FIELD_NONE = 0x00,
	KT_CULLER_3D_FIELD_NULLPTR = 0x01,
	KT_CULLER_3D_FIELD_DISTANCE = 0x02,
	// temp fix
	KT_CULLER_3D_FIELD_ALL = KT_CULLER_3D_FIELD_NULLPTR | KT_CULLER_3D_FIELD_DISTANCE
};

