#pragma once
#include <kotono_common/types.h>
enum KtSceneCullerField : u8
{
	KT_SCENE_CULLER_FIELD_NONE = 0x00,
	KT_SCENE_CULLER_FIELD_NULLPTR = 0x01,
	KT_SCENE_CULLER_FIELD_DISTANCE = 0x02,
	// temp fix
	KT_SCENE_CULLER_FIELD_ALL = KT_SCENE_CULLER_FIELD_NULLPTR | KT_SCENE_CULLER_FIELD_DISTANCE
};

