#pragma once
enum KtButton 
{
	KT_BUTTON_1 = 0,
	KT_BUTTON_2 = 1,
	KT_BUTTON_3 = 2,
	KT_BUTTON_4 = 3,
	KT_BUTTON_5 = 4,
	KT_BUTTON_6 = 5,
	KT_BUTTON_7 = 6,
	KT_BUTTON_8 = 7,
	KT_BUTTON_LAST = KT_BUTTON_8,
	KT_BUTTON_LEFT = KT_BUTTON_1,
	KT_BUTTON_RIGHT = KT_BUTTON_2,
	KT_BUTTON_MIDDLE = KT_BUTTON_3,
	KT_BUTTON_COUNT = 8
};